inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('prueba/', views.prueba, name='prueba'),
    path('segunda-vista/', views.segunda_vista, name='segunda_vista'),
    path('fecha-actual/', views.fecha_actual, name='fecha_actual'),
    path('saludar/', views.saludar, name='saludar'),
    path('saludar/<str:nombre>/<str:apellido>/', views.bienvenida, name='bienvenida'),
    
    # vistas comunes
    
    # v1 crear perro
    # path('crear-perro/<str:nombre>/<int:edad>/', views.crear_perro, name='crear_perro'),
    # v2 crear perro
    # path('perros/', views.listar_perros, name='listar_perros'),
    # path('perros/crear/', views.crear_perro, name='crear_perro'),
    # path('perros/eliminar/<int:perro_id>/', views.eliminar_perro, name='eliminar_perro'),
    # path('perros/modificar/<int:perro_id>/', views.modificar_perro, name='modificar_perro'),
    
    # CBV
    path('perros/', views.ListarPerros.as_view(), name='listar_perros'),
    path('perros/crear/', views.CrearPerro.as_view(), name='crear_perro'),
    path('perros/eliminar/<int:pk>/', views.EliminarPerro.as_view(), name='eliminar_perro'),
    path('perros/modificar/<int:pk>/', views.ModificarPerro.as_view(), name='modificar_perro'),
    path('perros/<int:pk>/', views.MostrarPerro.as_view(), name='mostrar_perro'),
]

miprimerdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView

app_name = 'usuario'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(template_name='usuario/logout.html'), name='logout'),
    path('registro/', views.registrarse, name='registrarse'),
    path('perfil/editar/', views.edicion_perfil, name='editar_perfil'),
    path('perfil/editar/password/', views.ModificarPass.as_view(), name='modificar_pass')
]

usuario/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class InfoExtra(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)

usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import authenticate, login as django_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from usuario.form import MiFormularioDeCreacionDeUsuarios, MiFormularioDeEdicionDeDatosDeUsuario
from django.urls import reverse_lazy
from usuario.models import InfoExtra

# Create your views here.

def login(request):
    
    if request.method == 'POST':
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            usuario = formulario.cleaned_data['username']
            contrasenia = formulario.cleaned_data['password']
            
            user = authenticate(username=usuario, password=contrasenia)
            
            django_login(request, user)
            
            InfoExtra.objects.get_or_create(user=user)
            
            return redirect('inicio:inicio')
        else:
            return render(request, 'usuario/login.html',  {'formulario': formulario})
            
    formulario = AuthenticationForm()
    return render(request, 'usuario/login.html',  {'formulario': formulario})


def registrarse(request):
    
    if request.method == 'POST':
        formulario = MiFormularioDeCreacionDeUsuarios(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('usuario:login')
        else:
            return render(request, 'usuario/registro.html', {'formulario': formulario})
            
    formulario = MiFormularioDeCreacionDeUsuarios()
    return render(request, 'usuario/registro.html', {'formulario': formulario})

@login_required
def edicion_perfil(request):
    info_extra_user = request.user.infoextra
    if request.method == 'POST':
        formulario = MiFormularioDeEdicionDeDatosDeUsuario(request.POST, request.FILES, instance=request.user)
        if formulario.is_valid():
            
            avatar = formulario.cleaned_data.get('avatar')
            if avatar:
                info_extra_user.avatar = avatar
                info_extra_user.save()
            
            formulario.save()
            return redirect('inicio:inicio')
    else:
        formulario = MiFormularioDeEdicionDeDatosDeUsuario(initial={'avatar': info_extra_user.avatar}, instance=request.user)
        
    return render(request, 'usuario/edicion_perfil.html', {'formulario': formulario})

class ModificarPass(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuario/modificar_pass.html'
    success_url = reverse_lazy('usuario:editar_perfil')

usuario/templates/usuario/edicion_perfil.html
{% extends 'base.html' %}

{% block title_head %}
<title>Edicion perfil</title>
{% endblock title_head %}

{% block h1_header %}
Editar perfil
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:editar_perfil' %} method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Guardar cambios</button>
    <button type='button'><a class="navbar-brand" href={% url 'usuario:modificar_pass' %}>Cambiar contrasenia</a></button>
</form>
{% endblock contenido %}

usuario/templates/usuario/login.html
{% extends 'base.html' %}

{% block title_head %}
<title>Login</title>
{% endblock title_head %}

{% block h1_header %}
Login
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:login' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Login</button>
</form>
{% endblock contenido %}

usuario/templates/usuario/logout.html
{% extends 'base.html' %}

{% block title_head %}
<title>Logout</title>
{% endblock title_head %}

{% block h1_header %}
Te deslogueaste con exito!
{% endblock h1_header %}

{% block contenido %}
{% endblock contenido %}

usuario/templates/usuario/modificar_pass.html
{% extends 'base.html' %}

{% block title_head %}
<title>Modificar pass</title>
{% endblock title_head %}

{% block h1_header %}
Modificar pass
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:modificar_pass' %} method="post">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Modificar</button>
</form>
{% endblock contenido %}

usuario/templates/usuario/registro.html
{% extends 'base.html' %}

{% block title_head %}
<title>Registrarse</title>
{% endblock title_head %}

{% block h1_header %}
Registro
{% endblock h1_header %}

{% block contenido %}
<form action={% url 'usuario:registrarse' %} method="POST">
    {% csrf_token %}
    <table>
        {{formulario}}
    </table>
    <button>Registrar</button>
</form>
{% endblock contenido %}