inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('prueba/', views.prueba, name='prueba'),
    path('segunda-vista/', views.segunda_vista, name='segunda_vista'),
    path('fecha-actual/', views.fecha_actual, name='fecha_actual'),
    path('saludar/', views.saludar, name='saludar'),
    path('saludar/<str:nombre>/<str:apellido>/', views.bienvenida, name='bienvenida'),
    
    # vistas comunes
    
    # v1 crear perro
    # path('crear-perro/<str:nombre>/<int:edad>/', views.crear_perro, name='crear_perro'),
    # v2 crear perro
    # path('perros/', views.listar_perros, name='listar_perros'),
    # path('perros/crear/', views.crear_perro, name='crear_perro'),
    # path('perros/eliminar/<int:perro_id>/', views.eliminar_perro, name='eliminar_perro'),
    # path('perros/modificar/<int:perro_id>/', views.modificar_perro, name='modificar_perro'),
    
    # CBV
    path('perros/', views.ListarPerros.as_view(), name='listar_perros'),
    path('perros/crear/', views.CrearPerro.as_view(), name='crear_perro'),
    path('perros/eliminar/<int:pk>/', views.EliminarPerro.as_view(), name='eliminar_perro'),
    path('perros/modificar/<int:pk>/', views.ModificarPerro.as_view(), name='modificar_perro'),
    path('perros/<int:pk>/', views.MostrarPerro.as_view(), name='mostrar_perro'),
]

miprimerdjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('inicio.urls')),
    path('usuario/', include('usuario.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from usuario import views
from django.contrib.auth.views import LogoutView

app_name = 'usuario'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', LogoutView.as_view(template_name='usuario/logout.html'), name='logout'),
    path('registro/', views.registrarse, name='registrarse'),
    path('perfil/editar/', views.edicion_perfil, name='editar_perfil'),
    path('perfil/editar/password/', views.ModificarPass.as_view(), name='modificar_pass')
]

inicio/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Perro(models.Model):
    nombre = models.CharField(max_length=20)
    edad = models.IntegerField()
    descripcion = RichTextField(null=True)
    
    def __str__(self):
        return f"Perro: {self.nombre} - Edad: {self.edad}"

inicio/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.http import HttpResponse
from datetime import datetime
from django.template import Template, Context, loader
from inicio.models import Perro
from django.shortcuts import render, redirect
from inicio.form import CrearPerroFormulario, BuscarPerroFormulario, ModificarPerroFormulario
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# v1
# def inicio(request):
#     return HttpResponse('Hola soy tu inicio')

# v2  
# def inicio(request):
#     archivo = open(r'C:\Users\cdbia\Desktop\proytectos\mi_primer_django\templates\inicio.html', 'r')
#     template = Template(archivo.read())
#     archivo.close()
#     segundos = datetime.now().second
#     diccionario = {
#         'mensaje': 'Este es el mensaje de inicio...',
#         'segundos': segundos,
#         'segundo_par': segundos%2 == 0,
#         'segundo_redondo': segundos%10 == 0,
#         'listado_de_numeros': list(range(25))
#     }
#     contexto = Context(diccionario)
#     renderizar_template = template.render(contexto)
#     return HttpResponse(renderizar_template)

# v3
# def inicio(request):
#     # archivo = open(r'C:\Users\cdbia\Desktop\proytectos\mi_primer_django\templates\inicio.html', 'r')
#     # template = Template(archivo.read())
#     # archivo.close()
    
#     template = loader.get_template('inicio.html')
    
#     segundos = datetime.now().second
#     diccionario = {
#         'mensaje': 'Este es el mensaje de inicio...',
#         'segundos': segundos,
#         'segundo_par': segundos%2 == 0,
#         'segundo_redondo': segundos%10 == 0,
#         'listado_de_numeros': list(range(25))
#     }
#     # contexto = Context(diccionario)
#     # renderizar_template = template.render(contexto)
    
#     renderizar_template = template.render(diccionario)
#     return HttpResponse(renderizar_template)

# v4
@login_required
def prueba(request):
    # template = loader.get_template('inicio.html')
    
    segundos = datetime.now().second
    diccionario = {
        'mensaje': 'Este es el mensaje de inicio...',
        'segundos': segundos,
        'segundo_par': segundos%2 == 0,
        'segundo_redondo': segundos%10 == 0,
        'listado_de_numeros': list(range(25))
    }
    # renderizar_template = template.render(diccionario)
    # return HttpResponse(renderizar_template)
    return render(request, 'inicio/prueba.html', diccionario)
    
def inicio(request):
    return render(request, 'inicio/inicio.html')

def segunda_vista(request):
    return HttpResponse('<h1>Soy la segunda vista!</h1>')

def fecha_actual(request):
    fecha = datetime.now()
    return HttpResponse(f'<h1>Fecha actual: {fecha}</h1>')

def saludar(request):
    return HttpResponse('Bienvenido/a!!!')

def bienvenida(request, nombre, apellido):
    return HttpResponse(f'Bienvenido/a {nombre.title()} {apellido.title()}!!!')

# v1
# def crear_perro(request, nombre, edad):
#     template = loader.get_template('crear_perro.html')
#     perro = Perro(nombre=nombre, edad=edad)
#     perro.save()
#     diccionario = {
#         'perro': perro,
#     }
#     renderizar_template = template.render(diccionario)
#     return HttpResponse(renderizar_template)

# v2
# def crear_perro(request, nombre, edad):
#     perro = Perro(nombre=nombre, edad=edad)
#     perro.save()
#     diccionario = {
#         'perro': perro,
#     }
#     return render(request, 'inicio/crear_perro.html', diccionario)


# v3
# def crear_perro(request):
#     print('=========================================')
#     print('=========================================')
#     print(request.POST)
#     print('=========================================')
#     print('=========================================')
#     print(request.GET)
#     print('=========================================')
#     print('=========================================')
    
#     diccionario = {}
    
#     if request.method == "POST":
#         perro = Perro(nombre=request.POST['nombre'], edad=request.POST['edad'])
#         perro.save()
#         diccionario['perro'] = perro
        
#     return render(request, 'inicio/crear_perro.html', diccionario)


# v4
# def crear_perro(request):
    
#     if request.method == "POST":
#         formulario = CrearPerroFormulario(request.POST)
#         if formulario.is_valid():
#             info = formulario.cleaned_data
#             perro = Perro(nombre=info['nombre'], edad=info['edad'])
#             perro.save()
#             return redirect('inicio:listar_perros')
#         else:
#             return render(request, 'inicio/crear_perro.html', {'formulario': formulario})
            
#     formulario = CrearPerroFormulario()
#     return render(request, 'inicio/crear_perro.html', {'formulario': formulario})
    
# def listar_perros(request):
#     formulario = BuscarPerroFormulario(request.GET)
#     if formulario.is_valid():
#         nombre_a_buscar = formulario.cleaned_data['nombre']
#         listado_de_perros = Perro.objects.filter(nombre__icontains=nombre_a_buscar)
    
#     formulario = BuscarPerroFormulario()
#     return render(request, 'inicio/listar_perros.html', {'formulario': formulario, 'perros': listado_de_perros})
    
# def eliminar_perro(request, perro_id):
    
#     perro = Perro.objects.get(id=perro_id)
#     perro.delete()
    
#     return redirect('inicio:listar_perros')

def modificar_perro(request, perro_id):
    perro_a_modificar = Perro.objects.get(id=perro_id)
    
    if request.method == 'POST':
        formulario = ModificarPerroFormulario(request.POST)
        if formulario.is_valid():
            info = formulario.cleaned_data
            perro_a_modificar.nombre = info['nombre']
            perro_a_modificar.edad = info['edad']
            perro_a_modificar.save()
            return redirect('inicio:listar_perros')
        else:
            return render(request, 'inicio/modificar_perro.html', {'formulario': formulario})
    
    formulario = ModificarPerroFormulario(initial={'nombre': perro_a_modificar.nombre, 'edad': perro_a_modificar.edad})
    return render(request, 'inicio/modificar_perro.html', {'formulario': formulario})


class CrearPerro(CreateView):
    model = Perro
    template_name = 'inicio/CBV/crear_perro_CBV.html'
    fields = ['nombre', 'edad', 'descripcion']
    success_url = reverse_lazy('inicio:listar_perros')
    
class ListarPerros(ListView):
    model = Perro
    template_name = "inicio/CBV/listar_perros_CBV.html"
    context_object_name = 'perros'
    
    def get_queryset(self):
        listado_de_perros = []
        formulario = BuscarPerroFormulario(self.request.GET)
        if formulario.is_valid():
            nombre_a_buscar = formulario.cleaned_data['nombre']
            listado_de_perros = Perro.objects.filter(nombre__icontains=nombre_a_buscar)
        return listado_de_perros
    
    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        contexto['formulario'] = BuscarPerroFormulario()
        return contexto
    

class ModificarPerro(LoginRequiredMixin, UpdateView):
    model = Perro
    template_name = "inicio/CBV/modificar_perro_CBV.html"
    fields = ['nombre', 'edad', 'descripcion']
    success_url = reverse_lazy('inicio:listar_perros')
    
class EliminarPerro(LoginRequiredMixin, DeleteView):
    model = Perro
    template_name = "inicio/CBV/eliminar_perro_CBV.html"
    success_url = reverse_lazy('inicio:listar_perros')
    
class MostrarPerro(DetailView):
    model = Perro
    template_name = "inicio/CBV/mostrar_perro_CBV.html"

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Template Base</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>
                <a class="navbar-brand" href={% url 'inicio:prueba' %}>Prueba</a>
                <a class="navbar-brand" href={% url 'inicio:listar_perros' %}>Perros</a>
                {% if request.user.is_authenticated %}
                {% if request.user.infoextra.avatar %}
                <img src={{request.user.infoextra.avatar.url}} alt="" height='40px'>
                {% endif %}
                <a class="navbar-brand" href={% url 'usuario:editar_perfil' %}>{{request.user.username}}</a>
                <a class="btn btn-secondary" href={% url 'usuario:logout' %}>Logout</a>
                {% else %}
                <a class="btn btn-primary" href={% url 'usuario:login' %}>Login</a>
                <a class="btn btn-primary" href={% url 'usuario:registrarse' %}>Registrarse</a>
                {% endif %}
            </div>
        </nav>

        {% block header %}
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">
                                {% block h1_header %}
                                Nuestra web intermedia de Django - Coderhouse
                                {% endblock h1_header %}
                            </h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header %}

        {% block contenido %}
        <p>Soy el template padre!</p>
        {% endblock contenido %}

        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/inicio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Este es el primer template que cree</h1>
    <p>{{mensaje}}</p>
    {% if segundo_redondo %}
    <p style='color: yellow;'>{{segundos}}</p>
    {% elif segundo_par %}
    <p style='color: red;'>{{segundos}}</p>
    {% else %}
    <p style='color: green;'>{{segundos}}</p>
    {% endif %}

    {% for numero in listado_de_numeros %}
    <p style='color: blue;'>{{numero}}</p>
    {% endfor %}


</body>
</html>